### PR TITLE
Refactoring complete

### PR DESCRIPTION
**Pull request by Blokkendoos**
Refactoring completed. That is, the GUI is now separated from the logic but the engraving code could still be improved/reorganised. Renamed to OOF-Engrave.

### CODE REVIEW

**Comment by jieter** [comment]
@Blokkendoos Wow, that looks like a lot of hard work!

I tried running the script quickly, it seems some assumptions you made about the python environment are not valid for mine. It would be nice if it's somewhat portable, so I'd expect it to run in a fresh python 2.7 virtualenv. Trying that leaves me with this `ImportError`:
```
~/OOF-Engrave-master$ mkvirtualenv fengrave
(fengrave) ~/OOF-Engrave-master$ ./oof-engrave.py 
Setting not found: imagefile
Setting not found: clean_paths
Traceback (most recent call last):
  File "./oof-engrave.py", line 296, in <module>
    from application.gui import Gui
  File "/home/jieter/Downloads/OOF-Engrave-master/application/gui.py", line 7, in <module>
    from vcarve_settings import VCarveSettings
  File "/home/jieter/Downloads/OOF-Engrave-master/application/vcarve_settings.py", line 1, in <module>
    from util import VERSION, OVD_AVAILABLE, OK, NOR, INV, NAN, position_window
ImportError: cannot import name OVD_AVAILABLE
```

**Comment by Blokkendoos** [comment]
Commited a fix for this but honestly I don't really understand why the exception handling (in externals.py) doesn't work as I expected.

**Comment by Blokkendoos** [comment]
Fixed per the latest two commits.

**Comment by jieter** [comment]
Yes, fixed now.

There seems to be some artifacts generated by the v-carving code, any idea?
Just noticed the yellow progress indicator message is not removed after the calculation is completed:

2018-03-29-085747_1420x896_scrot

**Comment by Blokkendoos** [comment]
This depends on the font used. e.g. the arcs in "romans.cxf" are ok. I have not investigated this (yet) as it is conform the original F-Engrave.
The statusbar color has been fixed.

**Comment by jieter** [comment]
Never noticed these artifacts with the original version, but I only used fonts converted from TTF for v-carving.

Let's merge!

**Pull request merged**
